-- Roadmap cards read in plain language; the eye-icon detail keeps the engineering text.
--
-- Two new columns on jira_tickets:
--   plain_summary — a short non-technical label ("Security work - Hardening")
--     shown ON the roadmap card in place of the raw Jira summary. Generated by
--     scripts/sync-jira.mjs from the summary/description/labels, and stored
--     rather than computed at render time so a human can overwrite a bad
--     auto-label without touching Jira or shipping code.
--   description  — the Jira description, flattened from ADF to plain text, so
--     the detail modal can show the full original wording. The modal already
--     renders `description` for RAID entries; Jira cards passed null.
--
-- Neither is ever written back to Jira. Jira stays the source of truth for
-- summary/description; these are the roadmap's own presentation layer.

ALTER TABLE jira_tickets
  ADD COLUMN IF NOT EXISTS plain_summary text,
  ADD COLUMN IF NOT EXISTS description text;

COMMENT ON COLUMN jira_tickets.plain_summary IS
  'Non-technical card label for the roadmap. Auto-generated on sync; safe to edit by hand — the sync only overwrites it when auto_summary is true.';
COMMENT ON COLUMN jira_tickets.description IS
  'Jira description flattened to plain text. Read-only mirror; never written back to Jira.';

-- A hand-edited label must survive the next sync. The sync sets this false when
-- a human overrides the label, and only regenerates rows where it is true.
ALTER TABLE jira_tickets
  ADD COLUMN IF NOT EXISTS auto_summary boolean NOT NULL DEFAULT true;

COMMENT ON COLUMN jira_tickets.auto_summary IS
  'True = plain_summary is machine-generated and the sync may replace it. Set false to pin a hand-written label.';
